"""Offline, reproducible Latin subsets. Run with vendor/fonts/requirements.txt."""
from pathlib import Path
import io
import hashlib
import json
import fontTools
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools import subset

ROOT = Path(__file__).resolve().parent.parent
VENDOR = ROOT / 'vendor/fonts'
assert fontTools.__version__ == '4.59.2', 'Install vendor/fonts/requirements.txt'

def sha(data):
    return hashlib.sha256(data).hexdigest()

def ranges(points):
    runs = []
    for point in sorted(points):
        if runs and point == runs[-1][1] + 1:
            runs[-1][1] = point
        else:
            runs.append([point, point])
    return ', '.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in runs)

sources = json.loads((VENDOR / 'sources.json').read_text())
faces = []
css = ['/* Generated by scripts/generate-fonts.py; ranges come from emitted WOFF2 cmaps. */']
for source in sources:
    data = (VENDOR / source['source']).read_bytes()
    assert sha(data) == source['sha256'], f"Source checksum mismatch: {source['source']}"
    font = TTFont(VENDOR / source['source'], recalcTimestamp=False)
    font = instantiateVariableFont(font, source['axes'], inplace=True)
    # Materialize instancer changes before subsetting variable glyph tables.
    intermediate = io.BytesIO()
    font.save(intermediate)
    intermediate.seek(0)
    font = TTFont(intermediate, recalcTimestamp=False)
    cmap = font.getBestCmap()
    # Latin + Latin Extended-A, combining accents, punctuation, currency and arrows.
    wanted = {c for c in cmap if 0x20 <= c <= 0x17F or 0x300 <= c <= 0x36F or 0x2000 <= c <= 0x21FF or c == 0x2212}
    options = subset.Options()
    options.recalc_timestamp = False
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=wanted)
    sub.subset(font)
    font.flavor = 'woff2'
    target = ROOT / 'assets/fonts' / source['output']
    target.parent.mkdir(parents=True, exist_ok=True)
    font.save(target)
    output = TTFont(target)
    points = sorted(output.getBestCmap())
    assert wanted == set(points), 'Subsetting silently dropped a requested glyph'
    face = {key: source[key] for key in ['family', 'output', 'weight']}
    face.update(bytes=target.stat().st_size, sha256=sha(target.read_bytes()), codepoints=points,
                axes={a.axisTag: [a.minValue, a.defaultValue, a.maxValue] for a in output['fvar'].axes})
    faces.append(face)
    css.append(f'''@font-face {{
  font-family: "{face['family']}";
  font-style: normal;
  font-weight: {face['weight']};
  font-display: swap;
  src: url("../fonts/{face['output']}") format("woff2");
  unicode-range: {ranges(points)};
}}''')
(ROOT / 'assets/css/fonts.css').write_text('\n\n'.join(css) + '\n')
(ROOT / 'assets/fonts/manifest.json').write_text(json.dumps({'cssSha256': sha((ROOT / 'assets/css/fonts.css').read_bytes()), 'faces': faces}, indent=2) + '\n')
print('Generated font bytes:', sum(face['bytes'] for face in faces))
